@startuml

title EMMT


state main as "Экран ввода формул": [Глобальное состояние]\nНет активного бокса\nПриложение ждет ввода игрока\nИзначально доступен один пустой бокс\n
state long_type as "Ввод текста":Всплывает окошко поверх основного интерфейса для набора текста\nДоступны - ввод текста, кнопки ОК, ОТМЕНА
state long_type_ok as "Добавление текста в бокс":Первый символ добавляется в активный бокс.\nДля остальных символов для каждого создается новый бокс.
state swipe_right as "Добавление бокса справа":Справа от активного бокса добавляется новый пустой
state swipe_up as "Добавление бокса сверху":Сверху от активного бокса добавляется новый пустой меньшего размера (вехний индекс в формуле). 
state swipe_up_right as "Добавление степени":Сверху справа от активного бокса добавляется новый пустой меньшего размера (степень в формуле).
state swipe_up_down as "Добавление нижнего индекса":Снизу справа от активного бокса добавляется новый пустой меньшего размера (индекс в формуле).
state swipe_down as "Добавление знаменателя":Снизу от активного бокса добавляется новый пустой такого же размера (знаменатель в формуле).
state swipe_not_box as "Смещение формулы":Формула на экране смещается в сторону обратную движению
state menu_type as "Добавление много-боксовой формулы (sin, cos, ln...)":На месте активного бокса создается нужное количество боксов\nСоздается пустой бокс в центре фоормлулы\nЭтот набор боксов воспринимается как один при дальнейшей работе
state swipe_left as "Удаление бокса":Бокс или группа боксов удаляются\nЕсли в боксе был текст, бокс заменяется на пустой.
state double_tap as "Перевод формулы в Latex": Текущая формула переводится в latex\nСохраняется в соответсвующий файл\nВыводится сообщение с получившейся формулой

main --> long_type: Долгое нажатие на любой свободный бокс
long_type --> long_type_ok: Тап по кнопке ОК
long_type --> main: Тап по кнопке ОТМЕНА
long_type_ok --> main
main --> swipe_right: Свайп вправо от лююого бокса
swipe_right --> main
main --> swipe_up: Свайп вверх от лююого бокса
swipe_up --> main
main --> swipe_up_right: Свайп вправо вверх от любого бокса
swipe_up_right --> main
main --> swipe_up_down: Свайп вправо вниз от любого бокса
swipe_up_down --> main
main --> swipe_down: Свайп вниз от любого бокса
swipe_down --> main
main --> swipe_not_box: Свайп в любую сторону на боксе и не в правой части экрана
swipe_not_box --> main
main --> menu_type: Перетаскивание формулы (функции) из правого верхнего раздела меню в любой бокс
menu_type --> main
main --> swipe_left: Свайп влево от любого бокса
swipe_left --> main
main --> double_tap: Двойной тап в нижней части экрана
double_tap --> main

@enduml 