@startuml

title Уровни

note "Переход из любого\nдругого глобального\nсостояния" as n

[*] --> auth: Пользователь\nне авторизован
[*] --> levels: Пользователь\nавторизован

levels --> reset: Тык на\nкрасный крестик
levels ---> choice: \n\nТык на\nуровень
levels ----> settings: Тык на шестерёнку
levels --> [*]: \n\nКнопка Home

reset --> auth: Игрок\nсогласился
reset -up-> levels: Игрок\nотказался
reset --> [*]: Кнопка Home

auth -up-> levels: Все данные\nвведены верно
auth --> [*]: Игрок\nотказался\nOR\nкнопка Home

note left
  Фоновый/Полный
  выход из приложения
end note

choice --> play: Переход в\nследующее\nглобальное\nсостояние

state auth as "Авторизация": Игрок вводит свои данные\nдля учета его достижений на\nсервере статистики
state reset as "Тотальный сброс": Игрок может сбросить\nвсе достижения и авторизацию\nлибо отказаться
state levels as "Просмотр уровней": Игрок скроллит меню\nв поисках интересного уровня
state choice as "Выбор уровня": Подсветка выбранного уровня
state play as "Игра": [Глобальное состояние]
state settings as "Настройки": [Глобальное состояние]

@enduml