@startuml

title Игра

note "Для упрощения не будем показывать\nпереходы из фонового режима,\nтак как возможен переход из этого состояния\nв любое нижеуказанное\nПо тем же причинам не будем показывать\nпереходы в состояние фонового/полного\nвыключения" as n

levels --> usual: Игрок нажал\nна выбранный\nуровень, который\nесть в оперативной\nпамяти
levels --> loading: Уровня нет в\nоперативной памяти

loading -left-> usual: \t\t\t\t\tУровень загрузился

usual ---> node: Игрок нажал\nна место\nв формуле
usual --> back: Тык на\nкнопку назад
usual ---> restart: Тык на\nкнопку\nперезапуска
usual ---> undo: Тык на\nкнопку возврата\nна шаг назад
usual --> usual: Игрок увеличил формулу\nжестами увеличения
usual --> loose: Время истекло

node --> rule: Игрок нажал\nна правило
node --> node: Игрок увеличил\nформулу\nжестами увеличения\nOR\nвыбрал\nдругое место\nв формуле
node -up--> usual: Игрок нажал\nна задний фон
node -left-> restart: Тык на\nкнопку\nперезапуска
node -left-> undo: Тык на\nкнопку возврата\nна шаг назад
node -right-> back: Тык на\nкнопку назад

rule --> win: Начальное выражение\nсведено к конечному
rule -up-> usual: Правило\nприменено

loose -up-> levels: Игрок решил\nвернуться в меню
loose -up-> usual: Игрок решил\nпройти заново

back -up-> levels

restart --> usual: Уровень\nзапускается\nзаново

undo --> usual: Возврат к\nсостоянию\nпрошлого шага

win -up-> levels: Игрок выбрал\nвозврат в меню
win --> usual: Игрок выбрал\nследующий/предыдущий\nуровень

state levels as "Уровни": [Глобальное состояние]
state win as "Победа": Ура!\nОтображается статистика прохождения\nс возможностью выбора:\n* вернуться в меню\n* перейти на следующий уровень\n* перейти на предыдущий уровень
state loose as "Поражение": Не проигрывал лишь тот, кто никогда не играл!\nОтображается сообщение о тайм ауте.\nИгрок может:\n* перезапустить уровень\n* вернуться в меню
state usual as "Базовое": Основное состояние игры.\nИгрок размышляет над задачей.\n* Первые 2 секунды отображается\n  приветственное сообщение\n* Если времени осталось меньше\n  11 секунд, отсчет выделяется красным\n* Конечную формулу можно спрятать
state node as "Выбор подформулы": Выделяется выбранная часть выражения.\nИгроку предлагается выбрать правило\nдля данного места формулы\nиз появившегося окошка с правилами,\nЛИБО! выбрать другое место в выражении
state rule as "Выбор правила": Выделяется выбранное\nигроком правило
state back as "Назад в меню": Выделяется кнопка\nвозврата в меню
state restart as "Перезапуск": Выделяется кнопка\nперезапуска уровня
state undo as "Шаг назад": Выделяется кнопка\nвозврата на\nшаг назад
state loading as "Загрузка": Уровень считывается\nв оперативую память

@enduml