@startuml

title Настройки

note "Переход из фонового\nрежима или из\nменю уровней" as n

[*] --> settings

settings ---> mark: Слайд/Тык\nпо звездочкам
settings ---> bug: Тык на кнопку\nотправки бага
settings --> back: Тык на кнопку назад
settings --> [*]: Кнопка Home

mark -up-> settings: Пользователь\nотправил оценку\nOR\nОтказался от\nэтой идеи
mark --> [*]: Кнопка Home

bug -up-> settings: Пользователь\nотправил ошибку\nOR\nОтказался от\nэтой идеи
bug --> [*]: Кнопка Home

note right
  Фоновый/Полный
  выход из приложения
end note

back --> levels: Переход в\nследующее\nглобальное\nсостояние

state bug as "Отправка бага": Здесь игрок может вводить\nкомментарии по пойманным\nим багам
state mark as "Оценивание": Здесь игрок может:\n* передумать и поменять оценку\n* оставить комментарий к оценке
state settings as "Просмотр настроек": Игрок копается в настройках
state back as "Возврат в меню": Пользователю подсвечивается\nкнопка возврата
state levels as "Уровни": [Глобальное состояние]

@enduml